# Generated by Django 3.2.6 on 2022-08-12 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunal',
            name='primerDocente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Administrador.docente', verbose_name='Primer Docente'),
            preserve_default=False,
        ),
    ]
