# Generated by Django 4.1 on 2022-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0004_alter_carrera_fechamodificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='periodoFin',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo de fin de Proyecto'),
        ),
    ]
