# Generated by Django 4.1 on 2022-08-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0005_alter_nivel_periodofin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='idEstudiantes',
            field=models.ManyToManyField(to='Administrador.estudiante', verbose_name='Listado de Estudiantes'),
        ),
    ]
