# Generated by Django 4.1 on 2022-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0006_alter_proyecto_idestudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='aula',
            field=models.PositiveIntegerField(choices=[(1, 'Aula 1'), (2, 'Aula 2'), (3, 'Aula 3'), (4, 'Aula 4'), (5, 'Aula 5'), (6, 'Aula 6'), (7, 'Aula 7'), (8, 'Aula 8'), (9, 'Aula 9')], max_length=2, verbose_name='Aula de defensa asignada'),
        ),
    ]
