# Generated by Django 4.1 on 2022-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0007_alter_tribunal_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaverificacion',
            name='nombreArchivo',
            field=models.PositiveIntegerField(choices=[(1, 'Solicitud de opción de titulación/Certificado de idoneidad.'), (2, 'Oficio o correo electrónico de llamado para elaborar el cronograma.'), (3, 'Cronograma de trabajo.')], max_length=100, verbose_name='Detalle'),
        ),
    ]
