# Generated by Django 4.1.1 on 2022-10-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0003_alter_seguimientodocumentacion_archivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proyecto')),
                ('idDocente', models.PositiveIntegerField(choices=[(3, 'Carlitos Guano'), (5, 'Jeffery Naranjo'), (7, 'Marco Yandun'), (12, 'Jorge Miranda'), (13, 'Samuel Lascano'), (16, 'Milton Del Hierro'), (17, 'Luis Patiño'), (18, 'Luis Sanipatin'), (19, 'Freddy Quinde'), (20, 'Felix Paguay')], verbose_name='Docente')),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.carrera', verbose_name='Carrera')),
                ('idEstudiantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Listado de Estudiantes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('descripcion', models.TextField(verbose_name='Temas a tratarse')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora de tutoría')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tutorias', verbose_name='Archivo de Tutoría')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListaVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('nombreArchivo', models.PositiveIntegerField(choices=[(1, 'Solicitud de opción de titulación/Certificado de idoneidad.'), (2, 'Oficio o correo electrónico de llamado para elaborar el cronograma.'), (3, 'Cronograma de trabajo.')], verbose_name='Detalle')),
                ('cumplimiento', models.BooleanField(default=False, verbose_name='Cumplimiento')),
                ('observacion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('idEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('nombreAvance', models.CharField(max_length=100, verbose_name='Nombre Avance')),
                ('observacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observacion')),
                ('porcentaje', models.PositiveIntegerField(default=0, verbose_name='Porcentaje completado')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentacion', verbose_name='Documento')),
                ('fechaEntrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
