# Generated by Django 3.2.6 on 2022-08-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nombre de la Carrera')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes', verbose_name='Fotografía')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes', verbose_name='Fotografía')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(blank=True, editable=False, null=True)),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.carrera', verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nombre de la Facultad')),
                ('sigla', models.CharField(max_length=20, verbose_name='Nombre corto de la Facultad')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Nivel')),
                ('periodoInicio', models.DateField(verbose_name='Periodo de inicio de Proyecto')),
                ('periodoFin', models.DateField(blank=True, null=True, verbose_name='Periodo de fin de Proyecto')),
                ('periodoActual', models.DateField(verbose_name='Periodo Actual')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proyecto')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(blank=True, editable=False, null=True)),
                ('idCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.carrera', verbose_name='Carrera')),
                ('idDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.docente', verbose_name='Docente')),
                ('idEstudiantes', models.ManyToManyField(to='App.Estudiante', verbose_name='Listado de Estudiantes')),
                ('idNivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.nivel', verbose_name='Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDefensa', models.DateTimeField()),
                ('aula', models.PositiveIntegerField(choices=[(1, 'Aula 1'), (2, 'Aula 2'), (3, 'Aula 3'), (4, 'Aula 4'), (5, 'Aula 5'), (6, 'Aula 6'), (7, 'Aula 7'), (8, 'Aula 8'), (9, 'Aula 9')], verbose_name='Aula de defensa asignada')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(blank=True, editable=False, null=True)),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ListaVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.PositiveIntegerField(choices=[(1, 'Solicitud de opción de titulación/Certificado de idoneidad.'), (2, 'Oficio o correo electrónico de llamado para elaborar el cronograma.'), (3, 'Cronograma de trabajo.')], verbose_name='Detalle')),
                ('observacion', models.TextField(blank=True, max_length=100, null=True, verbose_name='Observación')),
                ('cumplimiento', models.BooleanField(default=False, verbose_name='Cumplimiento')),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(blank=True, editable=False, null=True)),
                ('idEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.estudiante', verbose_name='Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='idFacultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.facultad', verbose_name='Facultad'),
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAvance', models.CharField(max_length=100, verbose_name='Nombre Avance')),
                ('observacion', models.CharField(max_length=100, verbose_name='Observacion')),
                ('porcentaje', models.PositiveIntegerField(verbose_name='Porcentaje completado')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.proyecto', verbose_name='Proyecto')),
            ],
        ),
    ]
