# Generated by Django 4.1.1 on 2022-10-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocentesSuplente',
            fields=[
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('uuID', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('docentesSuplentes', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Docentes Principales')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('fechaDefensa', models.DateTimeField()),
                ('aula', models.PositiveIntegerField(choices=[(1, 'Aula 1'), (2, 'Aula 2'), (3, 'Aula 3'), (4, 'Aula 4'), (5, 'Aula 5'), (6, 'Aula 6'), (7, 'Aula 7'), (8, 'Aula 8'), (9, 'Aula 9')], verbose_name='Aula de defensa asignada')),
                ('docentesPrincipales', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Docentes Principales')),
                ('docentesSuplentes', models.ManyToManyField(to='App.docentessuplente', verbose_name='Docentes Principales')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
