# Generated by Django 3.2.6 on 2022-09-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='archivo',
            field=models.FileField(default=1, upload_to='documentacion', verbose_name='Documento'),
            preserve_default=False,
        ),
    ]
