# Generated by Django 3.2.6 on 2022-09-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='idDocente',
            field=models.CharField(choices=[('2', 'Carlitos Guano'), ('4', 'Jeffery Naranjo'), ('6', 'Marco Yandun'), ('11', 'Jorge Miranda'), ('12', 'Samuel Lascano')], max_length=13, verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='primerDocente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, 'Carlitos Guano'), (3, 'Katherin Siza'), (4, 'Jeffery Naranjo'), (5, 'Morillo Reynaldo'), (6, 'Marco Yandun'), (7, 'Genoveva Chulde'), (8, 'Kevin Lopez'), (9, 'Kelly Mora'), (10, 'Patricio Narvaez'), (11, 'Jorge Miranda'), (12, 'Samuel Lascano')], max_length=15, verbose_name='Primer Docente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='primerDocenteSuplente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, 'Carlitos Guano'), (3, 'Katherin Siza'), (4, 'Jeffery Naranjo'), (5, 'Morillo Reynaldo'), (6, 'Marco Yandun'), (7, 'Genoveva Chulde'), (8, 'Kevin Lopez'), (9, 'Kelly Mora'), (10, 'Patricio Narvaez'), (11, 'Jorge Miranda'), (12, 'Samuel Lascano')], max_length=15, verbose_name='Primer Docente Suplente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='segundoDocente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, 'Carlitos Guano'), (3, 'Katherin Siza'), (4, 'Jeffery Naranjo'), (5, 'Morillo Reynaldo'), (6, 'Marco Yandun'), (7, 'Genoveva Chulde'), (8, 'Kevin Lopez'), (9, 'Kelly Mora'), (10, 'Patricio Narvaez'), (11, 'Jorge Miranda'), (12, 'Samuel Lascano')], max_length=15, verbose_name='Segundo Docente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='segundoDocenteSuplente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, 'Carlitos Guano'), (3, 'Katherin Siza'), (4, 'Jeffery Naranjo'), (5, 'Morillo Reynaldo'), (6, 'Marco Yandun'), (7, 'Genoveva Chulde'), (8, 'Kevin Lopez'), (9, 'Kelly Mora'), (10, 'Patricio Narvaez'), (11, 'Jorge Miranda'), (12, 'Samuel Lascano')], max_length=15, verbose_name='Segundo Docente Suplente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='terceroDocente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, 'Carlitos Guano'), (3, 'Katherin Siza'), (4, 'Jeffery Naranjo'), (5, 'Morillo Reynaldo'), (6, 'Marco Yandun'), (7, 'Genoveva Chulde'), (8, 'Kevin Lopez'), (9, 'Kelly Mora'), (10, 'Patricio Narvaez'), (11, 'Jorge Miranda'), (12, 'Samuel Lascano')], max_length=15, verbose_name='Tercer Docente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='terceroDocenteSuplente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, 'Carlitos Guano'), (3, 'Katherin Siza'), (4, 'Jeffery Naranjo'), (5, 'Morillo Reynaldo'), (6, 'Marco Yandun'), (7, 'Genoveva Chulde'), (8, 'Kevin Lopez'), (9, 'Kelly Mora'), (10, 'Patricio Narvaez'), (11, 'Jorge Miranda'), (12, 'Samuel Lascano')], max_length=15, verbose_name='Tercer Docente Suplente'),
        ),
    ]
