# Generated by Django 4.1.1 on 2022-10-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='idDocente',
            field=models.PositiveIntegerField(choices=[(7, 'Erick Josa'), (8, 'Erick Josa'), (9, 'Erick Josa'), (10, 'Adn asfd'), (11, 'nnm mm'), (12, 'Anderson Amilcar')], verbose_name='Docente'),
        ),
    ]
