# Generated by Django 4.1.1 on 2024-06-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombrearchivolistaverificacion',
            name='nombre',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
    ]
