# Generated by Django 4.1.1 on 2022-11-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_proyecto_iddocente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaverificacion',
            name='idEstudiante',
        ),
        migrations.RemoveField(
            model_name='listaverificacion',
            name='nombreArchivo',
        ),
        migrations.AddField(
            model_name='listaverificacion',
            name='archivo',
            field=models.PositiveIntegerField(choices=[(1, 'Solicitud de opción de titulación/Certificado de idoneidad.'), (2, 'Solicitud de aprobación del Plan del TIC.'), (3, 'Récord Académico'), (4, 'Notificación para la defensa del Plan del TIC.'), (5, 'Rúbrica de sustentación del Plan del TIC.'), (6, 'acta de sustentación del Plan del TIC.'), (7, 'Oficio de designación de tutor'), (8, 'Oficio o correo electrónico de llamado para elaborar el cronograma'), (9, 'Cronograma de trabajo'), (10, 'Plan del TIC definitivo (Digital).CD'), (11, 'Informe cuali-cuantitativo de la aprobación del Plan del TIC.'), (12, 'Informe de avance del TIC (1 por parcial luego de la aprobación del plan).'), (13, 'Informe de seguimiento de tutorías (1 por semestre)'), (14, 'Certificado de suficiencia de un idioma extranjero, otorgado por el centro de idiomas de la UPEC. '), (15, 'Certificado de aprobación de suficiencia en ofimática por parte del centro de TIC'), (16, 'Certificado de haber aprobado la asignatura de complementación de cultura física y estética'), (17, 'Certificado de la pasantía o de la práctica preprofesional '), (18, 'Certificado de vinculación con la sociedad.'), (19, 'Solicitud al director de carrera de la designación del tribunal para la predefensa.'), (20, 'Informe cuali-cuantitativo previo a la predefensa del informe del TIC.'), (21, 'Certificación antiplagio (Máx. 12%).'), (22, 'Récord académico indicando el cumplimiento del 100% de las asignaturas de la malla curricular'), (23, 'Designación de tribunal para la predefensa del informe de TIC.'), (24, 'Rúbrica de sustentación de la predefensa del informe de TIC.'), (25, 'Acta de sustentación de la predefensa del informe de TIC.'), (26, 'Informe final de cumplimiento de observaciones y recomendaciones por parte del tribunal.'), (27, 'Informe del Abstract emitido por el Centro de Idiomas'), (28, 'Orden de empastado'), (29, 'Certificado de encontrarse sin deuda con las dependencias universitarias'), (30, 'Informe final del TIC CD.'), (31, 'Solicitud de prorrogas (de ser el caso)')], default=1, verbose_name='Detalle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listaverificacion',
            name='idProyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.proyecto', verbose_name='Estudiante'),
            preserve_default=False,
        ),
    ]
