# Generated by Django 3.2.6 on 2022-09-21 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_avance_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='avance',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
