# Generated by Django 3.2.6 on 2022-08-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_usuarios_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='celular',
            field=models.CharField(default=1, max_length=10, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='idCarrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.carrera', verbose_name='Carrera'),
        ),
    ]
