# Generated by Django 4.1.1 on 2024-05-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_listavalidacioncarrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listavalidacioncarrera',
            name='nombreListaVer',
            field=models.ManyToManyField(blank=True, to='App.nombrearchivolistaverificacion'),
        ),
    ]
