# Generated by Django 4.1.1 on 2022-10-12 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_tribunal_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='aula',
            field=models.CharField(choices=[('1', 'Aula 1'), ('2', 'Aula 2'), ('3', 'Aula 3'), ('4', 'Aula 4'), ('5', 'Aula 5'), ('6', 'Aula 6'), ('7', 'Aula 7'), ('8', 'Aula 8'), ('9', 'Aula 9')], max_length=20, verbose_name='Aula de defensa asignada'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='fechaDefensa',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
