# Generated by Django 3.2.6 on 2022-09-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20220913_2121'),
        ('App', '0003_auto_20220913_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Nombre del Documento')),
                ('archivo', models.ImageField(upload_to='documentacion', verbose_name='Archivo')),
                ('idPerfiles', models.ManyToManyField(to='Usuarios.Perfiles', verbose_name='Disponible para')),
            ],
        ),
    ]
