# Generated by Django 3.2.6 on 2022-08-30 19:17

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20220827_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(error_messages={'unique': 'Un usuario con esta cédula ya se encuentra registrado'}, help_text='Se requiere al menos 10 catacteres', max_length=13, unique=True, validators=[App.models.Usuarios.UnicodeUsernameValidator], verbose_name='Usuario'),
        ),
    ]
