# Generated by Django 3.2.6 on 2022-09-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentacion', verbose_name='Archivo'),
        ),
    ]
