# Generated by Django 3.2.6 on 2022-09-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20220911_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='primerDocente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, ' '), (3, 'ERick Josa'), (4, 'Katherin Elizabeth Siza Imbaquingo'), (5, 'Ander Siza Imbaquingo')], max_length=15, verbose_name='Primer Docente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='primerDocenteSuplente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, ' '), (3, 'ERick Josa'), (4, 'Katherin Elizabeth Siza Imbaquingo'), (5, 'Ander Siza Imbaquingo')], max_length=15, verbose_name='Primer Docente Suplente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='segundoDocente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, ' '), (3, 'ERick Josa'), (4, 'Katherin Elizabeth Siza Imbaquingo'), (5, 'Ander Siza Imbaquingo')], max_length=15, verbose_name='Segundo Docente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='segundoDocenteSuplente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, ' '), (3, 'ERick Josa'), (4, 'Katherin Elizabeth Siza Imbaquingo'), (5, 'Ander Siza Imbaquingo')], max_length=15, verbose_name='Segundo Docente Suplente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='terceroDocente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, ' '), (3, 'ERick Josa'), (4, 'Katherin Elizabeth Siza Imbaquingo'), (5, 'Ander Siza Imbaquingo')], max_length=15, verbose_name='Tercer Docente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='terceroDocenteSuplente',
            field=models.CharField(choices=[(1, 'Georgina Arcos'), (2, ' '), (3, 'ERick Josa'), (4, 'Katherin Elizabeth Siza Imbaquingo'), (5, 'Ander Siza Imbaquingo')], max_length=15, verbose_name='Tercer Docente Suplente'),
        ),
    ]
