# Generated by Django 4.1.1 on 2022-11-20 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_listaverificacion_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreArchivoListaVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Trabajo de Integración Curricular (TIC)'), (2, 'Examen con Carácter Complexivo (ECC)')], default=1, verbose_name='Nombre del Proyecto')),
                ('orden', models.PositiveIntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='listaverificacion',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.nombrearchivolistaverificacion', verbose_name='Nombre del Archivo'),
        ),
    ]
