# Generated by Django 4.1.1 on 2022-10-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_tribunal_aula_alter_tribunal_fechadefensa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunal',
            name='docentesSuplentes',
        ),
        migrations.AddField(
            model_name='tribunal',
            name='docentesSuplentes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.docentessuplente', verbose_name='Docentes Principales'),
            preserve_default=False,
        ),
    ]
