# Generated by Django 3.2.6 on 2022-09-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20220921_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='usuarioModificacion',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='avance',
            name='usuarioRegistro',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='grupoexperto',
            name='usuarioModificacion',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='grupoexperto',
            name='usuarioRegistro',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='listaverificacion',
            name='usuarioModificacion',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='listaverificacion',
            name='usuarioRegistro',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuarioModificacion',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuarioRegistro',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='usuarioModificacion',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='usuarioRegistro',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='usuarioModificacion',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='usuarioRegistro',
            field=models.PositiveIntegerField(blank=True, editable=False, max_length=9, null=True),
        ),
    ]
