# Generated by Django 3.2.6 on 2022-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20220820_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='fechaCreacion',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fechaCreacion',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fechaCreacion',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='fechaCreacion',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='listaverificacion',
            name='fechaCreacion',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaCreacion',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='fechaCreacion',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False),
        ),
    ]
