# Generated by Django 4.1.1 on 2022-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_tribunal_docentessuplentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='defensa',
            field=models.BooleanField(default=False, verbose_name='Proyecto listo para pre/defensa'),
        ),
    ]
