# Generated by Django 3.2.6 on 2022-08-30 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20220830_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='informacion', verbose_name='Imagen')),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idEstudiantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Listado de Estudiantes'),
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre')),
                ('detalle', models.TextField(blank=True, max_length=100, null=True, verbose_name='Detalles')),
                ('imagen', models.ManyToManyField(blank=True, null=True, to='App.Imagenes', verbose_name='Imagen')),
            ],
        ),
    ]
