# Generated by Django 3.2.6 on 2022-08-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20220820_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='fechaModificacion',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fechaModificacion',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fechaModificacion',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='fechaModificacion',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='listaverificacion',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listaverificacion',
            name='fechaModificacion',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaModificacion',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='fechaModificacion',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
