# Generated by Django 3.2.6 on 2022-09-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20220915_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
