# Generated by Django 3.2.6 on 2022-08-30 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20220830_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='imagen',
            field=models.ManyToManyField(blank=True, to='App.Imagenes', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idEstudiantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Listado de Estudiantes'),
        ),
    ]
