# Generated by Django 3.2.6 on 2022-08-30 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20220830_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('nombre', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Perfiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='perfile',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idDocente',
            field=models.CharField(choices=[], max_length=13, verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idEstudiantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Listado de Estudiantes'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.perfiles', verbose_name='Perfil'),
        ),
    ]
