# Generated by Django 4.1.1 on 2023-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_fecha_tutoria_fechatutoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='idDocente',
            field=models.PositiveIntegerField(choices=[], verbose_name='Docente Tutor del Proyecto'),
        ),
    ]
