# Generated by Django 3.2.6 on 2022-08-30 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20220830_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='nombre',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Perfiles'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idDocente',
            field=models.CharField(choices=[(1, ' ')], max_length=13, verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idEstudiantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Listado de Estudiantes'),
        ),
    ]
