# Generated by Django 3.2.6 on 2022-08-30 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20220830_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='idEstudiantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Listado de Estudiantes'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='perfil',
            field=models.ForeignKey(blank=True, default='Estudiante', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.perfiles', verbose_name='Perfil'),
        ),
    ]
