# Generated by Django 3.2.6 on 2022-09-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20220921_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='porcentaje',
            field=models.PositiveIntegerField(default=0, verbose_name='Porcentaje completado'),
        ),
    ]
