# Generated by Django 3.2.6 on 2022-09-22 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_avance_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='fechaEntrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
