# Generated by Django 3.2.6 on 2022-08-30 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20220830_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunal',
            name='primerDocente',
            field=models.CharField(choices=[(1, 'Erick Josa')], default=1, max_length=15, verbose_name='Primer Docente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribunal',
            name='primerDocenteSuplente',
            field=models.CharField(choices=[(1, 'Erick Josa')], default=1, max_length=15, verbose_name='Primer Docente Suplente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribunal',
            name='segundoDocente',
            field=models.CharField(choices=[(1, 'Erick Josa')], default=1, max_length=15, verbose_name='Segundo Docente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribunal',
            name='segundoDocenteSuplente',
            field=models.CharField(choices=[(1, 'Erick Josa')], default=1, max_length=15, verbose_name='Segundo Docente Suplente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribunal',
            name='terceroDocente',
            field=models.CharField(choices=[(1, 'Erick Josa')], default=1, max_length=15, verbose_name='Tercer Docente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribunal',
            name='terceroDocenteSuplente',
            field=models.CharField(choices=[(1, 'Erick Josa')], default=1, max_length=15, verbose_name='Tercer Docente Suplente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idDocente',
            field=models.CharField(choices=[(1, 'Erick Josa')], max_length=13, verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idEstudiantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Listado de Estudiantes'),
        ),
    ]
