# Generated by Django 3.2.6 on 2022-09-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_avance_fechaentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='grupoexperto',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='listaverificacion',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
