# Generated by Django 3.2.6 on 2022-09-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20220922_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='idDocente',
            field=models.PositiveIntegerField(choices=[(3, 'Carlitos Guano'), (5, 'Jeffery Naranjo'), (7, 'Marco Yandun'), (12, 'Jorge Miranda'), (13, 'Samuel Lascano'), (16, 'Milton Del Hierro'), (17, 'Luis Patiño'), (18, 'Luis Sanipatin'), (19, 'Freddy Quinde'), (20, 'Felix Paguay')], verbose_name='Docente'),
        ),
    ]
