# Generated by Django 3.2.6 on 2022-09-08 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20220907_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='idEstudiantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Listado de Estudiantes'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='primerDocente',
            field=models.CharField(choices=[(2, 'Carlos Guano'), (3, 'Katherin Elizabeth Siza Imbaquingo'), (4, 'Georgina Arcos'), (5, 'Jeffery Naranjo'), (6, 'Pablo Acosta')], max_length=15, verbose_name='Primer Docente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='primerDocenteSuplente',
            field=models.CharField(choices=[(2, 'Carlos Guano'), (3, 'Katherin Elizabeth Siza Imbaquingo'), (4, 'Georgina Arcos'), (5, 'Jeffery Naranjo'), (6, 'Pablo Acosta')], max_length=15, verbose_name='Primer Docente Suplente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='segundoDocente',
            field=models.CharField(choices=[(2, 'Carlos Guano'), (3, 'Katherin Elizabeth Siza Imbaquingo'), (4, 'Georgina Arcos'), (5, 'Jeffery Naranjo'), (6, 'Pablo Acosta')], max_length=15, verbose_name='Segundo Docente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='segundoDocenteSuplente',
            field=models.CharField(choices=[(2, 'Carlos Guano'), (3, 'Katherin Elizabeth Siza Imbaquingo'), (4, 'Georgina Arcos'), (5, 'Jeffery Naranjo'), (6, 'Pablo Acosta')], max_length=15, verbose_name='Segundo Docente Suplente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='terceroDocente',
            field=models.CharField(choices=[(2, 'Carlos Guano'), (3, 'Katherin Elizabeth Siza Imbaquingo'), (4, 'Georgina Arcos'), (5, 'Jeffery Naranjo'), (6, 'Pablo Acosta')], max_length=15, verbose_name='Tercer Docente'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='terceroDocenteSuplente',
            field=models.CharField(choices=[(2, 'Carlos Guano'), (3, 'Katherin Elizabeth Siza Imbaquingo'), (4, 'Georgina Arcos'), (5, 'Jeffery Naranjo'), (6, 'Pablo Acosta')], max_length=15, verbose_name='Tercer Docente Suplente'),
        ),
        migrations.CreateModel(
            name='GrupoExperto',
            fields=[
                ('nombre', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Nombre del grupo')),
                ('idDocentes', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Docentes')),
            ],
        ),
    ]
