# Generated by Django 3.2.6 on 2022-09-08 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20220908_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoexperto',
            name='idDocentes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Docentes'),
        ),
        migrations.AlterField(
            model_name='grupoexperto',
            name='nombre',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Nombre del grupo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idEstudiantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Listado de Estudiantes'),
        ),
    ]
