# Generated by Django 4.1.1 on 2023-11-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_proyecto_iddocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='idDocente',
            field=models.PositiveIntegerField(verbose_name='Docente Tutor del Proyecto'),
        ),
    ]
