# Generated by Django 4.1.1 on 2023-12-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0019_alter_nombrearchivolistaverificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nombrearchivolistaverificacion',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='listaverificacion',
            name='idEstudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
