# Generated by Django 4.1.1 on 2022-10-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='periodoActual',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='periodoFin',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='periodoInicio',
        ),
    ]
