# Generated by Django 3.2.6 on 2022-09-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='perfil',
            field=models.ForeignKey(blank=True, default='Estudiante', null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.perfiles', verbose_name='Perfil'),
        ),
    ]
