# Generated by Django 3.2.6 on 2022-09-19 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientodocumentacion',
            name='idDocumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.documento', verbose_name='Documento'),
            preserve_default=False,
        ),
    ]
