# Generated by Django 3.2.6 on 2022-09-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='genero',
        ),
        migrations.AddField(
            model_name='carrera',
            name='genero',
            field=models.CharField(choices=[('Señor', 'Señor'), ('Señora', 'Señora')], default=1, max_length=10, verbose_name='Seleccione'),
            preserve_default=False,
        ),
    ]
