# Generated by Django 4.1.1 on 2022-10-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='formatoDocumentos', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientodocumentacion',
            name='fechaModificacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientodocumentacion',
            name='idDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.documento', verbose_name='documentacionEstudiante'),
        ),
    ]
