# Generated by Django 3.2.6 on 2022-09-11 17:47

import Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuarios_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(error_messages={'unique': 'Un usuario con esta cédula ya se encuentra registrado'}, help_text='Se requiere al menos 10 catacteres', max_length=13, unique=True, validators=[Usuarios.models.vcedula], verbose_name='Usuario'),
        ),
    ]
