# Generated by Django 4.1.1 on 2022-10-09 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_carrera_fechamodificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientodocumentacion',
            name='archivo',
            field=models.FileField(upload_to='documentacionEstudiante', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='seguimientodocumentacion',
            name='idDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.documento', verbose_name='Documento'),
        ),
        migrations.CreateModel(
            name='GrupoExperto',
            fields=[
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Nombre del grupo')),
                ('idDocentes', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Docentes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
