# Generated by Django 3.2.6 on 2022-09-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20220913_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='usuario/firma', verbose_name='Firma'),
        ),
    ]
