# Generated by Django 3.2.6 on 2022-09-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_usuarios_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to='documentacion', verbose_name='Archivo')),
                ('estado', models.BooleanField(blank=True, choices=[(False, 'Pendiente'), (True, 'Aprobado'), (None, 'Rechazado')], default=False, null=True, verbose_name='Estado del archivo')),
                ('idPerfiles', models.ManyToManyField(to='Usuarios.Perfiles', verbose_name='Disponible para')),
            ],
        ),
    ]
