# Generated by Django 4.1.1 on 2022-10-12 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_seguimientodocumentacion_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constantes',
            fields=[
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='* Nombre')),
                ('valor', models.CharField(max_length=100, verbose_name='* Valor')),
                ('descripcion', models.TextField(max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
