# Generated by Django 3.2.6 on 2022-09-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='idDocumentos',
            field=models.ManyToManyField(to='Usuarios.Documento', verbose_name='Documentos'),
        ),
    ]
