# Generated by Django 4.1.1 on 2023-04-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_documento_id_alter_documento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='idPerfiles',
            field=models.ManyToManyField(blank=True, to='Usuarios.perfiles', verbose_name='Disponible para'),
        ),
        migrations.AddField(
            model_name='seguimientodocumentacion',
            name='idDocumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.documento', verbose_name='Documento'),
            preserve_default=False,
        ),
    ]
