# Generated by Django 4.1.1 on 2023-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_documento_idperfiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='abreviatura',
            field=models.CharField(choices=[('MSc.', 'MSc.'), ('Mg.', 'Mg.'), ('Mtr.', 'Mtr.'), ('PhD.', 'PhD.')], default='MSc.', max_length=8, verbose_name='Abreviatura'),
        ),
    ]
