# Generated by Django 3.2.6 on 2022-09-15 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_usuarios_iddocumentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='idDocumentos',
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.BooleanField(blank=True, choices=[(False, 'Pendiente'), (True, 'Aprobado'), (None, 'Rechazado')], default=None, null=True, verbose_name='Estado del archivo'),
        ),
        migrations.CreateModel(
            name='SeguimientoDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.documento', verbose_name='Documento')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
