# Generated by Django 3.2.6 on 2022-09-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_auto_20220915_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='estado',
        ),
        migrations.AddField(
            model_name='seguimientodocumentacion',
            name='estado',
            field=models.BooleanField(blank=True, choices=[(False, 'Pendiente'), (True, 'Aprobado'), (None, 'Rechazado')], default=None, null=True, verbose_name='Estado del archivo'),
        ),
    ]
