# Generated by Django 4.1.1 on 2023-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_usuarios_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='tipoTitulo',
            field=models.CharField(choices=[('Ingeniería.', 'Ingeniería.'), ('Licenciatura.', 'Licenciatura')], default='Ingeniería', help_text='Ingeniería en Informática', max_length=20, verbose_name='Tipo del título a obtener'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Genero'),
        ),
    ]
