# Generated by Django 4.1.1 on 2023-05-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_carrera_tipotitulo_usuarios_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1, verbose_name='Genero'),
        ),
    ]
