# Generated by Django 4.1.1 on 2023-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_alter_usuarios_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='fechaMemorandoTutor',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='memorandoTutor',
            field=models.CharField(blank=True, editable=False, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='tipoTitulo',
            field=models.CharField(choices=[('Ingeniería.', 'Ingeniería.'), ('Licenciatura.', 'Licenciatura'), ('Administrador Público.', 'Administrador Público')], default='Ingeniería', help_text='Ingeniería en Informática', max_length=40, verbose_name='Tipo del título a obtener'),
        ),
    ]
