# Generated by Django 4.1.1 on 2023-10-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_usuarios_fechamemorandotutor_usuarios_memorandotutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cohorte',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
