# Generated by Django 4.1.1 on 2023-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_usuarios_cohorte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['pk', 'nombre']},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='esExtranjero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cohorte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
