# Generated by Django 4.1.1 on 2023-11-19 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_alter_nivel_options_usuarios_esextranjero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('mesInicio', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=10, verbose_name='Mes Inicio')),
                ('yearInicio', models.PositiveIntegerField(verbose_name='Año inicio')),
                ('mesFin', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=10, verbose_name='Mes Fin')),
                ('yearFin', models.PositiveIntegerField(verbose_name='Año Fin')),
                ('cohorte', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Nombre de Cohorte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cohorte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.cohorte', verbose_name='Cohorte'),
        ),
    ]
