# Generated by Django 4.1.1 on 2023-11-18 16:52

import Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_alter_nivel_options_usuarios_esextranjero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(error_messages={'unique': 'Un usuario con esta cédula ya se encuentra registrado'}, help_text='Se requiere al menos 10 catacteres', max_length=13, unique=True, validators=[Usuarios.models.vcedula], verbose_name='Usuario'),
        ),
    ]
