# Generated by Django 4.1.1 on 2023-11-29 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0012_cohorte_alter_usuarios_cohorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneracionFirmas',
            fields=[
                ('fechaCreacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, editable=False, null=True)),
                ('usuarioRegistro', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('usuarioModificacion', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('uuIDFirma', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('firmaUsuario', models.ImageField(blank=True, null=True, upload_to='usuario/firma', verbose_name='Firma')),
                ('idUsuario', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['-perfil__nombre']},
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.generacionfirmas'),
        ),
    ]
