# Generated by Django 4.1.1 on 2023-11-29 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0015_alter_usuarios_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.generacionfirmas'),
        ),
    ]
