# Generated by Django 4.1.1 on 2023-12-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0016_alter_usuarios_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='abreviatura',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='genero',
        ),
    ]
