# Generated by Django 4.1.1 on 2023-12-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0017_remove_carrera_abreviatura_remove_carrera_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimientodocumentacion',
            options={'ordering': ['idUsuario__first_name']},
        ),
    ]
